apiVersion: rhdh.redhat.com/v1alpha1
kind: Backstage
metadata:
  name: developer-hub
spec:
  application:
    dynamicPluginsConfigMapName: dynamic-plugins-rhdh
    appConfig:
      mountPath: /opt/app-root/src
      configMaps:
      - name: "app-config-rhdh"
    extraEnvs:
      secrets:
        - name: rhdh-secret               
    replicas: 1
    route:
      enabled: true
  database:
    enableLocalDb: true