kind: Secret
apiVersion: v1
metadata:
  name: rhdh-secret
stringData:
  BACKEND_SECRET: <Replace with your secret>
  AUTH_AZURE_CLIENT_ID: <Replace with your client ID>
  AUTH_AZURE_CLIENT_SECRET: <Replace with your client secret>
  AUTH_AZURE_TENANT_ID: <Replace with your tenant id>
  ADO_PAT: <replace with your token>
  basedomain: <Replace with your basedomain>
  organization: <replace with your organization>
type: Opaque